# Generated by Django 5.2 on 2025-04-08 17:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyTip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Safety Tip ID')),
                ('category', models.CharField(choices=[('personal', 'Personal'), ('machinery', 'Machinery'), ('hazards', 'Hazards'), ('fire', 'Fire'), ('slips', 'Slips'), ('handling', 'Handling'), ('emergency', 'Emergency'), ('workplace', 'Workplace'), ('supervision', 'Supervision'), ('behavior', 'Behavior')], max_length=20, verbose_name='Tip Category')),
                ('tips_note', models.TextField(verbose_name='Safety Tip Notes')),
                ('tips_image', models.ImageField(upload_to='safety_tips_images/', verbose_name='Tip Illustration Image')),
            ],
            options={
                'verbose_name': 'Safety Tip',
                'verbose_name_plural': 'Safety Tips',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('department', models.CharField(blank=True, max_length=30, null=True, verbose_name='Department Block')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Alert ID')),
                ('category', models.CharField(choices=[('fire', 'Fire'), ('electrical', 'Electrical'), ('chemical', 'Chemical'), ('accident', 'Accident'), ('incident', 'Incident'), ('other', 'Other')], max_length=20, verbose_name='Alert Type')),
                ('location', models.CharField(max_length=30, verbose_name='Alert Location')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, verbose_name='Severity Level')),
                ('status', models.CharField(choices=[('new', 'New'), ('dismissed', 'Dismissed'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='new', max_length=15, verbose_name='Alert Status')),
                ('description_notes', models.TextField(blank=True, null=True, verbose_name='Description and Notes')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Alert Creation Date')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Resolution Notes')),
                ('response_time', models.IntegerField(blank=True, null=True, verbose_name='Response Time (minutes)')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_acknowledged', to=settings.AUTH_USER_MODEL, verbose_name='Acknowledged By')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_reported', to=settings.AUTH_USER_MODEL, verbose_name='Reported By')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Audit Log ID')),
                ('role', models.CharField(choices=[('worker', 'Worker'), ('safety_officer', 'Safety Officer'), ('admin', 'Admin'), ('agent', 'Agent')], max_length=20, verbose_name='User Role')),
                ('action', models.CharField(choices=[('created', 'Created'), ('dismissed', 'Dismissed'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], max_length=20, verbose_name='Action Performed')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Action Timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('device_info', models.TextField(blank=True, null=True, verbose_name='Device Information')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='ping.alert', verbose_name='Related Alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Notification ID')),
                ('medium', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10, verbose_name='Notification Medium')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Time Sent')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10, verbose_name='Notification Status')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='ping.alert', verbose_name='Related Alert')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL, verbose_name='Notification Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
