# Generated by Django 5.2 on 2025-04-18 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='acknowledged_by',
        ),
        migrations.AddField(
            model_name='alert',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed By'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10, verbose_name='Severity Level'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('dismissed', 'Dismissed'), ('confirmed', 'Confirmed'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='new', max_length=15, verbose_name='Alert Status'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('dismissed', 'Dismissed'), ('confirmed', 'Confirmed'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], max_length=20, verbose_name='Action Performed'),
        ),
    ]
