# Generated by Django 5.2 on 2025-04-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0003_remove_alert_acknowledged_by_alert_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number'),
        ),
    ]
